// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace SferedApi.Components
{
    using Grasshopper.Kernel;
    using Rhino.Geometry;
    using SferedApi;
    using SferedApi.Properties;
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    
    public class BulidInnerLoops : GH_Component
    {
        public BulidInnerLoops() : base(SD.Starter + "Build Inner Loops", SD.Starter + "Inner L", SD.CopyRight + "Add inner loops to a face of a brep. this is like grasshopper's trim, but direct.", SD.PluginTitle, SD.PluginCategory8)
        {
        }
        
        protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "", 0);
            pManager.AddIntegerParameter("Face index", "Fi", "face Index", 0, 0);
            pManager.AddCurveParameter("Curve", "C", "closed, on-surface curve to trim with", 1);
        }
        
        protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "New Brep with the addition", 0);
            pManager.AddIntegerParameter("Trim Indices", "Ti", "Trim Indices", 1);
        }
        
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            Brep brep = null;
            int face = -1;
            List<Curve> objA = new List<Curve>();
            DA.GetData<Brep>(0, ref brep);
            DA.GetData<int>(1, ref face);
            DA.GetDataList<Curve>(2, objA);
            if (((brep == null) || (face == -1)) || object.ReferenceEquals(objA, null))
            {
                this.AddRuntimeMessage(20, "input bad");
            }
            else
            {
                DA.SetDataList(1, brep.BuildInnerLoops(face, objA, 1));
                DA.SetData(0, brep);
            }
        }
        
        protected override Bitmap Icon =>
            Resources.Sfered_Iconified;
        
        public override Guid ComponentGuid =>
            new Guid("9e95e206-0e98-48f0-9416-e9e5057db19c");
    }
}
