// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace SferedApi.Components
{
    using Grasshopper.Kernel;
    using Rhino.Geometry;
    using SferedApi;
    using SferedApi.Properties;
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    
    public class BulidInnerFaces : GH_Component
    {
        public BulidInnerFaces() : base(SD.Starter + "Build Inner Faces", SD.Starter + "Inner F", SD.CopyRight + "Add inner loops to a face of a brep, and build faces and outer loops. this is like grasshopper's trim, but directly applied to a face.", SD.PluginTitle, SD.PluginCategory8)
        {
        }
        
        protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "", (GH_ParamAccess)0);
            pManager.AddIntegerParameter("Face index", "Fi", "face Index", (GH_ParamAccess)0, 0);
            pManager.AddCurveParameter("Curve", "C", "closed, on-surface curve to trim with", (GH_ParamAccess)1);
        }
        
        protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "New Brep with the addition", (GH_ParamAccess)0);
            pManager.AddIntegerParameter("Face Indices", "Ti", "Indices of new faces", (GH_ParamAccess)1);
        }
        
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            Brep brep = null;
            int face = -1;
            List<Curve> objA = new List<Curve>();
            DA.GetData<Brep>(0, ref brep);
            DA.GetData<int>(1, ref face);
            DA.GetDataList<Curve>(2, objA);
            if (((brep == null) || (face == -1)) || object.ReferenceEquals(objA, null))
            {
                this.AddRuntimeMessage((GH_RuntimeMessageLevel)20, "input bad");
            }
            else
            {
                DA.SetDataList(1, brep.BuildInnerFaces(face, objA));
                DA.SetData(0, brep);
            }
        }
        
        protected override Bitmap Icon =>
            Resources.Sfered_Iconified;
        
        public override Guid ComponentGuid =>
            new Guid("7dad9fc0-01d2-4f19-94d4-fdc9b45f27f2");
    }
}
