// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace SferedApi
{
    using Grasshopper.Kernel;
    using Rhino.Geometry;
    using SferedApi.Properties;
    using System;
    using System.Drawing;
    
    public class CopyBrep : GH_Component
    {
        public CopyBrep() : base(SD.Starter + "DeepCopy Brep", SD.Starter + "DeepCopy", SD.CopyRight + "Duplicate a Brep. The Sfered brep components deviate from grasshopper protocol; The brep before and after an 'add' component are the exact same brep, for the sake of running speed.Use this component if a copy is actualy desired. ", SD.PluginTitle, SD.PluginCategory9)
        {
        }
        
        protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "Original Brep", (GH_ParamAccess)0);
        }
        
        protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "Copied Brep", (GH_ParamAccess)0);
        }
        
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            Brep original = null;
            DA.GetData<Brep>(0, ref original);
            DA.SetData(0, BrepFunctions.DeepCopy(original, 0.0));
        }
        
        protected override Bitmap Icon =>
            Resources.Sfered_Iconified;
        
        public override Guid ComponentGuid =>
            new Guid("7812441b-e48a-49a9-a238-ef7b9db0d22a");
    }
}
