// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace SferedApi
{
    using System;
    using System.Collections.Generic;
    
    public class CurvePartition
    {
        public List<List<Curve>> outer;
        public List<List<Curve>> inner;
        
        public CurvePartition(List<List<Curve>> outer, List<List<Curve>> inner)
        {
            this.outer = outer;
            this.inner = inner;
        }
        
        public void AddCurves()
        {
        }
        
        public void AddInnerLoop(List<Curve> innerLoop)
        {
            this.inner.Add(innerLoop);
        }
        
        public void AddOuterLoop(List<Curve> outerLoop)
        {
            this.outer.Add(outerLoop);
        }
    }
}
