// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace Gazelle
{
    using System;
    
    internal enum IntersectionOrientation
    {
        Positive,
        Negative,
        neutral
    }
}
