//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SferedApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SferedApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;about&quot;: {
        ///    &quot;TODO&quot;: &quot;todo&quot;
        ///  },
        ///  &quot;extra&quot;: {
        ///    &quot;TODO&quot;: &quot;todo&quot;
        ///  },
        ///  &quot;main&quot;: {
        ///    &quot;bridge&quot;: {
        ///      &quot;2nd_adj_ampl_topbridge_curve_rim_side&quot;: &quot;2 to 3&quot;,
        ///      &quot;adj_ampl_bottombridge_at_angled_noseplane_towards_bridge&quot;: &quot;2 to 3.5&quot;,
        ///      &quot;adj_ampl_bottombridge_at_angled_noseplane_towards_rim&quot;: &quot;1&quot;,
        ///      &quot;adj_ampl_topbridge_at_angled_nosepane_towards_bridge&quot;: &quot;.5 to 1&quot;,
        ///      &quot;adj_ampl_topbridge_at_angled_noseplane_towards_rim&quot;: &quot;2&quot;,
        ///      &quot;bottom_back_bridge_Y&quot;: &quot;-1.2&quot;,
        ///      &quot;bottom_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json1 {
            get {
                return ResourceManager.GetString("json1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ghenv.Component.Name = &quot;SI: Pythonify&quot;
        ///ghenv.Component.NickName = &quot;SI: PY&quot;
        ///ghenv.Component.Description = &quot;converts C# nodes into python usable node&quot;
        ///
        ///
        ///
        ///print(&quot;hello world&quot;)
        ///a = &quot;hello world&quot;
        ///b = x + y
        /// 
        /// import Rhino as rc
        ///import Rhino.Geometry as rcg
        ///import scriptcontext as sc
        ///
        ///import clr
        ///clr.AddReference(&quot;Grasshopper&quot;)
        ///import Grasshopper as gh
        ///import rhinoscriptsyntax as rs 
        ///
        ///from copy import deepcopy as copy
        ///import string
        ///
        ///# get the letter curve data 
        ///DATA_LETTERLINES = C
        ///
        ///class  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;data a&quot;: {
        ///        &quot;surface top&quot;: [ 
        ///            [10,9,4,0],
        ///            [10,1,11,12],
        ///            [12,2,7,6],
        ///            [4,3,[18,5,19],6],
        ///            [5,17,8]
        ///        ],
        ///        &quot;surface bot&quot;: [
        ///            [18,9,13,17],
        ///            [8,7,19,14],
        ///            [11,13,14]
        ///        ],
        ///        &quot;loft&quot;: [11,7,19,8,17,18,9],
        ///        &quot;edges&quot;: [0,1,2,3]
        ///        },  
        ///		
        ///    &quot;data b&quot;: {
        ///        &quot;surface top&quot;: [ 
        ///            [13,14,15,16],
        ///            [9,10,11,12],
        ///            [0,[4,5],28,27] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextInsertJson {
            get {
                return ResourceManager.GetString("TextInsertJson", resourceCulture);
            }
        }
    }
}
