// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace SferedApi
{
    using Grasshopper.Kernel;
    using SferedApi.Properties;
    using System;
    using System.Drawing;
    
    public class ConsolePrinter : GH_Component
    {
        public bool IsExpired;
        
        public ConsolePrinter() : base(SD.Starter + "Console", SD.Starter + "Console", SD.CopyRight + "Toying around with how to setup a correct brep", SD.PluginTitle, SD.PluginCategory10)
        {
            this.IsExpired = false;
            Debug.SetListener(this);
        }
        
        protected override void RegisterInputParams(GH_Component.GH_InputParamManager p)
        {
        }
        
        protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager p)
        {
            p.AddTextParameter("Lines", "Lines", "All debug lines printed", (GH_ParamAccess)1);
        }
        
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            DA.SetDataList(0, Debug.GetAllStrings());
            this.IsExpired = false;
        }
        
        protected override Bitmap Icon =>
            Resources.Sfered_Iconified;
        
        public override Guid ComponentGuid =>
            new Guid("0d653a1e-90ae-49c7-ba7e-eb5b3b49b9c2");
    }
}
