// Generated by .NET Reflector from D:\Sfered\Gazelle\Remnants\SferedApi_brep_manipulation.dll
namespace SferedApi
{
    using Grasshopper.Kernel;
    using Rhino.Geometry;
    using SferedApi.Properties;
    using System;
    using System.Drawing;
    
    public class AddEdge : GH_Component
    {
        public AddEdge() : this(SD.Starter + "AddEdge", SD.Starter + "Edge", SD.CopyRight ?? "", SD.PluginTitle, SD.PluginCategory7)
        {
        }
        
        protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "", 0);
            pManager.AddCurveParameter("Curve", "C", "3D curve to create the edge from", 0);
            pManager.AddIntegerParameter("Vertex Index Start", "Vs", "index from starting vertex", 0);
            pManager.AddIntegerParameter("Vertex Index End", "Ve", "index from ending vertex", 0);
        }
        
        protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
        {
            pManager.AddBrepParameter("Brep", "B", "New Brep with the addition", 0);
            pManager.AddIntegerParameter("Edge Index", "Ei", "Edge index", 0);
        }
        
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            Brep brep = null;
            Curve curve = null;
            int vertexFrom = -1;
            int vertexTo = -1;
            DA.GetData<Brep>(0, ref brep);
            DA.GetData<Curve>(1, ref curve);
            DA.GetData<int>(2, ref vertexFrom);
            DA.GetData<int>(3, ref vertexTo);
            if (((brep == null) || ((curve == null) || (!curve.get_IsValid() || (vertexFrom == -1)))) || (vertexTo == -1))
            {
                this.AddRuntimeMessage(20, "input bad");
            }
            else
            {
                DA.SetData(1, brep.AddEdge(curve, vertexFrom, vertexTo));
                DA.SetData(0, brep);
            }
        }
        
        protected override Bitmap Icon =>
            Resources.Sfered_Iconified;
        
        public override Guid ComponentGuid =>
            new Guid("14aa5806-8bbc-43c0-b0e9-acd5a3dc6174");
    }
}
